# linear and angular speed limits for the robot
max_v: 0.15 #0.4 # m/s
max_w: 0.25 #0.8 # rad/s
# observation rate fo the robot
frame_rate: 10 # Hz
graph_rate: 0.5 # Hz  

# topic names (modify for different robots/nodes)
# vel_teleop_topic: /cmd_vel_mux/input/teleop 
# vel_navi_topic: /cmd_vel_mux/input/navi
# vel_recovery_topic: /cmd_vel_mux/input/recovery

# waffle机器人
# vel_teleop_topic: /cmd_vel
# vel_navi_topic: /cmd_vel
# vel_recovery_topic: /cmd_vel

#jackel
vel_teleop_topic: /cmd_vel
vel_navi_topic: /cmd_vel
base_scan_topic: /front/scan
odom_topic: /odometry/filtered
depth_topic: /front/depth/image_raw